### ISSUE TITLE
Run issues and dep installation problems and a mistake in README.md, with source command pointing to wrong location

### ISSUE THREAD

**Issue by juozaspo** [Amulet-Team/Amulet-Core#60] opened 2019-12-01 11:44 UTC
### Is your feature request related to a problem? Please describe.
The command `source /ENV/bin/activate` described in README.md section for Linux/Mac at the line that says `Activate the environment` has an argument pointing to wrong location, where using the slash before path name points to root directory of the system instead of the one in current directory. Removing the slash or adding a dot might fix it. But there comes another prombem: installed pip version does not install requirements in order, ~even when using the latest version of it (by upgrading it using command `pip install --upgrade pip`~ It appears the latest version works almost ok. After doing workarounds to make it build properly (installing dependencies manually one by one) the editor finally can be run. Though it fails with another error when all the dependencies are installed
**Describe the solution you'd like**
Changing the source command in README.md (by removing the leading slash or adding dot on the first parameter) might help to fix some problems. Other than that ~the requirement installation order might needed to be fixed too, or if it is a pip bug, this should be reported to the developers. Also~ fixing the paths needed for runtime might fix the program unable to be run correctly, not mentioning of adding the correct documentation of running to in the README.md.

### Describe alternatives you've considered
Use `cat requirements.txt | xargs -I{} sh -c 'pip install {}'` as a workaround for buggy pip command. or upgrade pip inside env.
### Additional context
**Python:** 3.7.5
**Pip provided by system:** 9.0.1
Initial failure running env w/o changing the command line to correct one:
```
$ python3.7 -m venv ENV
$ LC_ALL=C source /ENV/bin/activate
bash: /ENV/bin/activate: No such file or directory
```
After fixing that the env can no be entered and `pip install -r requirements.txt` command can be run. Though the command might fail if `cython` is not installed (as the pip does not appear to do the installation in correct order). Install cython by running `pip install cython` inside the env then try the command again.
```
(ENV) juozas@xubuntu:~/test/Amulet-Core$ pip install -r requirements.txt 
Collecting git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 2))
  Cloning git://github.com/Amulet-Team/Amulet-NBT.git to /tmp/pip-ezvv2zaf-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ezvv2zaf-build/setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ezvv2zaf-build/
```
After installing cython the command fails again with another error pointing to numpy that's supposedly missing (it should be installed first, is this a pip bug?)
```
$ pip install -r requirements.txt 
Collecting git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 2))
  Cloning git://github.com/Amulet-Team/Amulet-NBT.git to /tmp/pip-fnuu9n92-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-fnuu9n92-build/setup.py", line 7, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fnuu9n92-build/
```
Fixed by installing correct version of numpy first then trying again, by running command `pip install $(grep -i numpy requirements.txt) `. If compilation fails on next attempt to install deps from requirements.txt, install `python3.7-dev` outside the env then try again. The error should say that `Python.h` is not found or similar. After that it can be run even though it still might fail during runtime as shown below.
```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from amulet.command_line import enhanced_prompt, reduced_prompt, CommandHandler
  File "/home/juozas/test/Amulet-Core/amulet/command_line/__init__.py", line 1, in <module>
    from .command_api import (
  File "/home/juozas/test/Amulet-Core/amulet/command_line/command_api.py", line 12, in <module>
    from amulet.api.world_loader import load_world
ModuleNotFoundError: No module named 'amulet.api.world_loader'
```

**Comment by gentlegiantJGC** [comment] 2019-12-01 12:41
This is the kind of well laid out bug report I like to see. The core library has changed quite a lot lately and I don't think main has been updated to reflect that. Tbh I don't even know what main does. If you want a UI see the Amulet UI repository

**Comment by Podshot** [comment] 2019-12-01 13:19
Thanks for the report! I’ll update the README when I get the opportunity later today

**Comment by Podshot** [comment] 2019-12-01 19:59
I do find it odd that pip is not installing dependency packages before it's dependents, especially since when I run `pip install -r requirements.txt` everything is installed in the order it should be. Could you give me the version of pip that is installed in the virtual environment?

**Comment by juozaspo** [comment] 2019-12-01 20:49
Pip version coming with my installation
`pip 9.0.1 from /home/juozas/test/Amulet-Core/ENV/lib/python3.7/site-packages (python 3.7)`
Installation works fine after upgrading pip.

**Comment by Podshot** [comment] 2019-12-02 00:59
Ok, so it seems the outdated pip version caused the dependency installation steps to fail, I'll include that as a new step in the README as well

**Comment by juozaspo** [comment] 2019-12-02 05:40
As in https://github.com/Amulet-Team/Amulet-Map-Editor/issues/1#issuecomment-560236944 updating pip does not solve the thing entirely. Pip still request dependencies not in correct order, as shown in the comment the compilation fails as numpy is not found.

**Comment by juozaspo** [comment] 2019-12-02 11:55
Found out that I had an outdated setuptools package, coming by default with Ubuntu. Updating that fixed everything. Since this is solved by updating setuptools, this should be added to the Readme to avoid any further future issues. Also it's worth to check by outdated packages using pip, by running command 'pip list -o', but first it must be upgraded to latest version, as old version is broken.
```
(ENV) $ pip install --upgrade pip #first upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 574kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.3.1
(ENV) $ pip list -o #check for outdated python packages
Package    Version Latest Type 
---------- ------- ------ -----
setuptools 39.0.1  42.0.2 wheel
(ENV) juozas@xubuntu:~/test/Amulet-Core$ pip install --upgrade setuptools #upgrade setup tools to fix pip requirement installation
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
     |████████████████████████████████| 583kB 1.4MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
Successfully installed setuptools-42.0.2
(ENV) juozas@xubuntu:~/test/Amulet-Core$ pip install -r requirements.txt 
Collecting git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 2))
  Cloning git://github.com/Amulet-Team/Amulet-NBT.git to /tmp/pip-req-build-fg2ut1d2
  Running command git clone -q git://github.com/Amulet-Team/Amulet-NBT.git /tmp/pip-req-build-fg2ut1d2
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 2)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting git+git://github.com/gentlegiantJGC/PyMCTranslate.git (from -r requirements.txt (line 3))
  Cloning git://github.com/gentlegiantJGC/PyMCTranslate.git to /tmp/pip-req-build-la47jobx
  Running command git clone -q git://github.com/gentlegiantJGC/PyMCTranslate.git /tmp/pip-req-build-la47jobx
Collecting numpy==1.15.2
  Using cached https://files.pythonhosted.org/packages/98/44/94cc2e139b611b16458384ff3b9c87f217144b5915b0a9798c07a7295437/numpy-1.15.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting cython==0.29.13
  Downloading https://files.pythonhosted.org/packages/f1/d3/03a01bcf424eb86d3e9d818e2082ced2d512001af89183fca6f550c32bc2/Cython-0.29.13-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 1.4MB/s 
Building wheels for collected packages: amulet-nbt
  Building wheel for amulet-nbt (PEP 517) ... done
  Created wheel for amulet-nbt: filename=amulet_nbt-0.0.0-cp37-cp37m-linux_x86_64.whl size=700160 sha256=b2905be7a4e8416ebce89948f32fbbfa87c7c42210d622a471b1fbab75501c22
  Stored in directory: /tmp/pip-ephem-wheel-cache-a69pm8hg/wheels/a1/b4/77/1a9f37cb872d273d31616ab609753a8222bd71743679514298
Successfully built amulet-nbt
Installing collected packages: numpy, cython, amulet-nbt, pymctranslate
    Running setup.py install for pymctranslate ... done
Successfully installed amulet-nbt-0.0.0 cython-0.29.13 numpy-1.15.2 pymctranslate-0.0.0
```

**Comment by Podshot** [comment] 2019-12-03 19:23
Since the issue is resolved for this repository, I'll be closing this issue

**Closed by Podshot** 2019-12-03 19:23 UTC
Labels: OS/Linux, good first issue
